project_name: dobind
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
      - darwin
      - linux
      - windows
archives:
- name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
